args: 
   environment: none
spring:
   datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://172.17.1.56:3306/newwd?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&serverTimezone=PRC&useSSL=false
      username: root
      password: 123456
      
   jpa:
     database: MYSQL
     hibernate.ddl-auto: none 
     hibernate.naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
     show-sql: true 
   profiles:
     active: "profileActive"
   messages:
     always-use-message-format: false
     basename: enums
     cache-seconds: -1
     encoding: UTF-8
     fallback-to-system-locale: true

server:
   error:
     path: /error 
   
logging.file: D:/data/mylog
logging.path: myLog.log

     
     
     