args:
  environment: none
spring:
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/newwd?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&serverTimezone=PRC&useSSL=false
      username: root
      password: wd123.com
    ######################### Druid连接池的配置信息  ##############
# elasticsearch集群名称，默认的是elasticsearch
        ##  data:
        ##      elasticsearch:
        ##        cluster-name: docker-cluster
        ##    #节点的地址 注意api模式下端口号是9300，千万不要写成9200
        ##        cluster-nodes: 172.16.100.81:9300
        ##    #是否开启本地存储
    ##        repositories:
    ##              enable: true
#  data:
#    elasticsearch:
#      cluster-name: elasticsearch-cluster
#      cluster-nodes: 172.16.100.41:9300,172.16.100.43:9300,172.16.100.81:9300
#      local: true
#      repositories:
#        enabled: true
  druid:
      initialSize: 5                                 #初始化连接大小
      minIdle: 5                                     #最小连接池数量
      maxActive: 20                                  #最大连接池数量
      maxWait: 60000                                 #获取连接时最大等待时间，单位毫秒
      timeBetweenEvictionRunsMillis: 60000           #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      minEvictableIdleTimeMillis: 300000             #配置一个连接在池中最小生存的时间，单位是毫秒
      validationQuery: SELECT 1 FROM DUAL            #测试连接
      testWhileIdle: true                            #申请连接的时候检测，建议配置为true，不影响性能，并且保证安全性
      testOnBorrow: false                            #获取连接时执行检测，建议关闭，影响性能
      testOnReturn: false                            #归还连接时执行检测，建议关闭，影响性能
      poolPreparedStatements: false                  #是否开启PSCache，PSCache对支持游标的数据库性能提升巨大，oracle建议开启，mysql下建议关闭
      maxPoolPreparedStatementPerConnectionSize: 20  #开启poolPreparedStatements后生效
      filters: stat,wall,log4j                       #配置扩展插件，常用的插件有=>stat:监控统计  log4j:日志  wall:防御sql注入
      connectionProperties: 'druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000'  #通过connectProperties属性来打开mergeSql功能;慢SQL记录
  application:
      name: spirng-boot-rabbitmq
  rabbitmq:
      host: 172.16.100.57
      port: 5672
      username: admin
      password: admin
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  ##单服务器
  redis:
    sentinel:
      master: mymaster
      nodes: 172.16.100.81:26379,172.16.100.80:26379
#    ## 连接池最大连接数（使用负值表示没有限制）
#    jedis:
#      pool:
#        max-active: 300
#        ## 连接池最大阻塞等待时间（使用负值表示没有限制）
#        max-wait: -1
#        ## 连接池中的最大空闲连接
#        max-idle: 100
#        ## 连接池中的最小空闲连接
#        min-idle: 20
#    cluster:
#      nodes:
#
#             - 172.16.100.81:6379
    ## Redis数据库索引(默认为0)
    database: 0

  ## 连接超时时间（毫秒）
    timeout: 60000
  jpa:
    database: MYSQL
    hibernate.ddl-auto: none
    hibernate.naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true


  profiles:
    active: @profileActive@
  messages:
    basename: i18n.messages
    cache-second: 3600
    encoding: UTF-8
    always-use-message-format: false
    fallback-to-system-locale: true
    # 上传文件情况
  servlet:
    multipart:
      max-file-size: 100MB # 最大支持文件大小
      max-request-size: 100MB # 最大支持请求大小


hbase:
  conf:
    confMaps:
      hbase.zookeeper.quorum : 172.16.100.28:2181,172.16.100.29:2181,172.16.100.30:2181



server:
  error:
    path: /error
  port: 9877
#  servlet:
#    session:
#      timeout: PT5S

mybatis:
  typeAliasesPackage: cn.zzdz.domain
  mapperLocations: classpath:/mybatismapper/*.xml
  #logging:
  #path: log/mylog
  #file: myLog.log
    #level:
    #org:
    #hibernate: ERROR
    #springframework:
  #web: DEBUG
#fdfs:
#  so-timeout: 1501
#  connect-timeout: 2000
#  tracker-list:
#    -172.16.100.81:22122
# 分布式文件系统fastdfs配置
fdfs:
  # socket连接超时时长
  soTimeout: 1500
  connectTimeout: 600
  pool:
    # 从池中借出的对象的最大数目
    max-total: 153
    # 获取连接时的最大等待毫秒数100
    max-wait-millis: 102
  # 缩略图生成参数，可选
  thumbImage:
    width: 150
    height: 150
  # 跟踪服务器tracker_server请求地址,支持多个，这里只有一个，如果有多个在下方加- x.x.x.x:port
  trackerList:
    - 10.88.1.135:22122
    #- 172.16.100.81:22122
    #- 10.88.1.94:22122
    #- 172.16.100.80:22122 group1/M00/00/00/ClgBYF0WuKWAN8kNAAMtk3_3ZEM153.jpg
  #
  # 存储服务器storage_server访问地址
  web-server-url: http://10.88.1.98/

#elk集群地址
elasticsearch:
  ip: 172.16.100.56,172.16.100.57,172.16.100.58
  port: 9300
  #集群名称
  cluster:
    name: elasticsearch-cluster
  #连接池
  pool: 5