args:
  environment: none
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/newwd?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&serverTimezone=PRC&useSSL=false
    username: root
    password: wd123.com
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  ##单服务器
  redis:
    cluster:
      nodes: 192.168.159.129:7001,192.168.159.129:7002,192.168.159.129:7003,192.168.159.129:7004,192.168.159.129:7005,192.168.159.129:7006
  ## 连接池最大连接数（使用负值表示没有限制）
    jedis:
      pool:
        max-active: 300
        ## 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        ## 连接池中的最大空闲连接
        max-idle: 100
        ## 连接池中的最小空闲连接
        min-idle: 20
  ## Redis数据库索引(默认为0)
    database: 0

  ## 连接超时时间（毫秒）
    timeout: 60000
  jpa:
    database: MYSQL
    hibernate.ddl-auto: none
    hibernate.naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
  profiles:
    active: @profileActive@
  messages:
    basename: i18n.messages
    cache-second: 3600
    encoding: UTF-8
    always-use-message-format: false
    fallback-to-system-locale: true

server:
  error:
    path: /error
  port: 8080
#  servlet:
#    session:
#      timeout: PT5S

mybatis:
  typeAliasesPackage: cn.zzdz.domain
  mapperLocations: classpath:/mybatismapper/*.xml
  #logging:
  #path: log/mylog
  #file: myLog.log
    #level:
    #org:
    #hibernate: ERROR
    #springframework:
  #web: DEBUG