args:
  environment: none
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/newwd?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&serverTimezone=PRC&useSSL=false
    username: root
    password: wd123.com

  jpa:
    database: MYSQL
    hibernate.ddl-auto: none
    hibernate.naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
  profiles:
    active: @profileActive@
  messages:
    basename: i18n.messages
    cache-second: 3600
    encoding: UTF-8
    always-use-message-format: false
    fallback-to-system-locale: true

server:
  error:
    path: /error
  port: 8080
mybatis:
  typeAliasesPackage: cn.zzdz.domain
  mapperLocations: classpath:/mybatismapper/*.xml
  #logging:
  #path: log/mylog
  #file: myLog.log
    #level:
    #org:
    #hibernate: ERROR
    #springframework:
  #web: DEBUG